# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.9'

services:
  djangobackend:
    container_name: Adeeny-djangobackend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /build
    volumes:
      - .:/Adeeny
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - mysql-db
    ports:
     - "8000:8000"
  
  mysql-db:
    container_name: Adeeny-mysqldb
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}

    ports:
      - "3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
  static_volume:
  media_volume: