services:
  djangobackend:
    container_name: Adeeny-djangobackend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    # expose:
    #   - "8000"
    env_file:
      - .env
    depends_on:
      - mysql-db
    ports:
      - "8000:8000"
    networks:
      - adeeny-network

  mysql-db:
    container_name: Adeeny-mysqldb
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - "3306:3306"
    # expose:
    #   - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - adeeny-network

networks:
  adeeny-network:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume:
