# Generated by Django 5.0.6 on 2024-08-23 13:58

import apps.donation_management.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='WAQF Title')),
                ('donors_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Donations')),
                ('phone_numnber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('upload_image', models.FileField(blank=True, null=True, upload_to=apps.donation_management.models.ProjectDonation.user_directory_path, verbose_name='Upload Image')),
                ('imams_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Imam's Name")),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card')], max_length=250, null=True, verbose_name='Payment Type')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount')),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Target Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
