# Generated by Django 5.0.6 on 2024-08-07 12:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='donors_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Donations'),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='phone_numnber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='projectdonation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card')], max_length=250, null=True, verbose_name='Payment Type'),
        ),
    ]
