#!/bin/bash

# Exit the script if any command fails
set -o errexit

# Exit the script if any command in a pipeline fails
set -o pipefail

# Exit the script if any undefined variable is used
set -o nounset

if [ "$DATABASE" = "mysql" ]
then
    echo "Waiting for mysql..."

    while ! nc -z $SQL_HOST $SQL_PORT; do
      sleep 0.1
    done

    echo "PostgreSQL started"
fi

python manage.py flush --no-input
python manage.py migrate

exec "$@"