# Generated by Django 5.0.6 on 2024-10-11 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('amount', models.CharField(max_length=100)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_issuer', models.CharField(choices=[('MTN', 'mtn'), ('vodafone', 'vodafone'), ('AIRTELTIGO', 'airteltigo')], max_length=100)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('external_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_issuer', models.CharField(choices=[('MTN', 'mtn'), ('vodafone', 'vodafone'), ('AIRTELTIGO', 'airteltigo')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
