# Generated by Django 5.0.6 on 2024-09-30 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_collections_external_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='id',
        ),
        migrations.AlterField(
            model_name='collections',
            name='account_issuer',
            field=models.CharField(choices=[('MTN', 'mtn'), ('vodafone', 'vodafone'), ('AIRTELTIGO', 'airteltigo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='collections',
            name='external_transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
