# Generated by Django 5.0.6 on 2024-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('IMAM', 'Imam'), ('ASSOCIATE', 'Associate'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
