# Generated by Django 5.0.6 on 2024-09-06 15:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to=apps.users.models.upload_to, verbose_name='Profile Picture'),
        ),
    ]
