# Generated by Django 5.0.6 on 2024-09-19 12:02

import apps.mosque_management.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mosque Location')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('image', models.FileField(blank=True, null=True, upload_to='user_directory_path')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Mosque Name')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('imam', models.CharField(max_length=250, verbose_name="Imam's Name")),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mosque Location')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('image', models.ImageField(upload_to=apps.mosque_management.models.upload_to, verbose_name='Mosque Image')),
                ('certificate', models.FileField(upload_to=apps.mosque_management.models.upload_to)),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Content')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=250)),
                ('time', models.TimeField(default='n/a', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=250)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('speaker_name', models.CharField(default='n/a', max_length=250)),
                ('sermon_type', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'video'), ('DOCUMENT', 'Document')], default='n/a', max_length=50)),
                ('docs', models.FileField(blank=True, null=True, upload_to=apps.mosque_management.models.upload_to)),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.mosque_management.models.upload_to)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.mosque_management.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
