# Generated by Django 5.0.6 on 2024-07-10 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='imam',
            field=models.CharField(max_length=250, verbose_name="Imam's Name"),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Mosque Name'),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
