# Generated by Django 5.0.6 on 2024-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='mosque image'),
        ),
    ]
