# Generated by Django 5.0.6 on 2024-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Mosque Name'),
        ),
    ]
