# Generated by Django 5.0.6 on 2024-07-16 15:48

import apps.mosque_management.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_management', '0002_alter_mosque_location_alter_mosque_imam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=250)),
                ('time', models.CharField(default='n/a', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='mosque_image',
        ),
        migrations.AddField(
            model_name='annoucement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annoucement',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='annoucement',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.mosque_management.models.Mosque.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
