# Generated by Django 5.0.6 on 2024-09-20 13:28

import apps.mosque_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_management', '0002_alter_mosque_certificate_alter_mosque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='certificate',
            field=models.FileField(upload_to=apps.mosque_management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='image',
            field=models.ImageField(upload_to=apps.mosque_management.models.upload_to, verbose_name='Mosque Image'),
        ),
    ]
